# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Test
  jobs:
  - job: Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: ShellScript@2
      displayName: Run sample test
      inputs:
        scriptPath: './sample-test.sh'
      env:
        SHAKEDOWN_URL: https://duckduckgo.com

- stage: Test2
  jobs:
  - job: TestDockerCompose
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerCompose@0
      inputs:
        dockerComposeFile: 'docker-compose/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'run'
        arguments: 'app'
        currentWorkingDirectory: '$(System.DefaultWorkingDirectory)/docker-compose'

- stage: Deploy
  jobs:
  - job: Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: ShellScript@2
      displayName: Run sample test
      inputs:
        scriptPath: './sample-test.sh'
      env:
        SHAKEDOWN_URL: https://duckduckgo.com
  - deployment: Deploy
    displayName: deploy to dockerhub
    pool:
      vmImage: 'Ubuntu-latest'
    environment: 'dockerhub'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Docker@2
            displayName: Build and push the image
            inputs:
              containerRegistry: 'dockerhub-robwhitby'
              repository: 'robwhitby/shakedown'
              command: 'buildAndPush'
              Dockerfile: './Dockerfile'
              buildContext: '.'
              tags: '$(tag)'
