# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: ShellScript@2
      displayName: Run sample test
      inputs:
        scriptPath: './sample-test.sh'
        args: '-u https://duckduckgo.com'
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build the image
      inputs:
        containerRegistry: 'docker.io/robwhitby'
        repository: 'shakedown-ap'
        command: 'buildAndPush'
        Dockerfile: './Dockerfile'
        buildContext: '.'
        tags: |
          $(tag)
          latest
